"""initial

Revision ID: 46d501f44259
Revises: 
Create Date: 2026-05-16 19:29:00.558351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46d501f44259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_search")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tree_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('raw_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clean_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nlp_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disambiguation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tree_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tree_nodes_doc_id'), 'tree_nodes', ['doc_id'], unique=False)
    op.create_table('atoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('raw_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clean_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nlp_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disambiguation', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{"pronoun_map": []}'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tree_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_atoms_doc_id', 'atoms', ['doc_id'], unique=False)
    op.create_index('ix_atoms_embedding', 'atoms', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atom_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=256), nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clean_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['atom_id'], ['atoms.id'], ),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_mentions')
    op.drop_index('ix_atoms_embedding', table_name='atoms', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_index('ix_atoms_doc_id', table_name='atoms')
    op.drop_table('atoms')
    op.drop_index(op.f('ix_tree_nodes_doc_id'), table_name='tree_nodes')
    op.drop_table('tree_nodes')
    op.drop_table('canonical_entities')
    # ### end Alembic commands ###
